# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # use node:16
      - name: use Node.js 16.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      # yarn install and build, pm2 start
      - name: yarn install & build & pm2 start
        run: |
          npm install -g yarn
          npm install -g pm2
          yarn install
          yarn build
          # /home/action/actions-runner/_work/_tool/node/16.15.0/x64/bin/pm2 reload linkkey-app
          /home/action/actions-runner/_work/_tool/node/16.15.0/x64/bin/pm2 start yarn --name "linkkey-app" --interpreter bash -- start
        env:
          CI: true
